TOPICS = [
    {
        "name": "Earth’s Interior",
        "notes": [
            {
                "heading": "Overview",
                "points": [
                    "Earth’s interior refers to the internal structure beneath the surface",
                    "Not directly observable; studied through indirect evidence",
                    "Divided into crust, mantle, and core",
                    "Understanding interior helps explain earthquakes, volcanoes, and plate tectonics",
                    "Very important for UPSC"
                ]
            },
            {
                "heading": "Sources of Information",
                "points": [
                    "Direct sources: mining, drilling (limited depth)",
                    "Indirect sources: seismic waves (most important)",
                    "Meteorites provide clues about composition",
                    "Gravity and magnetic studies",
                    "Density calculations of Earth"
                ]
            },
            {
                "heading": "Seismic Waves (Very Important)",
                "points": [
                    "Generated by earthquakes",
                    "Help understand Earth's interior structure",
                    "Three types: P-waves, S-waves, Surface waves",
                    "Travel at different speeds through materials",
                    "Used to detect layers inside Earth"
                ]
            },
            {
                "heading": "Types of Seismic Waves",
                "points": [
                    "P-waves (Primary): travel through solids, liquids, gases (fastest)",
                    "S-waves (Secondary): travel only through solids",
                    "Surface waves: travel on surface, most destructive",
                    "S-waves do not pass through liquid outer core",
                    "Helps identify state of Earth's layers"
                ]
            },
            {
                "heading": "Shadow Zones",
                "points": [
                    "Regions where seismic waves are not detected",
                    "P-wave shadow zone indicates liquid outer core",
                    "S-wave shadow zone confirms absence in liquids",
                    "Helps determine internal structure",
                    "Important conceptual topic"
                ]
            },
            {
                "heading": "Layers of the Earth",
                "points": [
                    "Crust – outermost layer (5–70 km thick)",
                    "Mantle – extends up to 2900 km",
                    "Core – extends to center (6371 km)",
                    "Layers differ in composition and density",
                    "Temperature and pressure increase with depth"
                ]
            },
            {
                "heading": "Crust",
                "points": [
                    "Thin outer layer",
                    "Two types: continental and oceanic",
                    "Continental crust thicker and less dense",
                    "Oceanic crust thinner and denser",
                    "Composed mainly of silica and alumina (SIAL)"
                ]
            },
            {
                "heading": "Mantle",
                "points": [
                    "Largest layer (~83% of Earth’s volume)",
                    "Composed mainly of silica and magnesium (SIMA)",
                    "Semi-solid (plastic behavior)",
                    "Upper mantle includes asthenosphere",
                    "Convection currents drive plate tectonics"
                ]
            },
            {
                "heading": "Core",
                "points": [
                    "Innermost layer",
                    "Composed mainly of iron and nickel (NIFE)",
                    "Outer core is liquid",
                    "Inner core is solid",
                    "Source of Earth’s magnetic field"
                ]
            },
            {
                "heading": "Discontinuities",
                "points": [
                    "Moho discontinuity – between crust and mantle",
                    "Gutenberg discontinuity – between mantle and core",
                    "Lehmann discontinuity – within core",
                    "Marked by change in seismic wave velocity",
                    "Important for understanding structure"
                ]
            },
            {
                "heading": "Temperature, Pressure and Density",
                "points": [
                    "Increase with depth",
                    "Core temperature ~5000–6000°C",
                    "Pressure extremely high at center",
                    "Density highest in core",
                    "Affects physical state of materials"
                ]
            }
        ],
        "mcqs": {
            "basic": [
                {
                    "question": "Earth has how many main layers?",
                    "options": ["2", "3", "4", "5"],
                    "answer": "3"
                },
                {
                    "question": "Outer core is:",
                    "options": ["Solid", "Liquid", "Gas", "Vacuum"],
                    "answer": "Liquid"
                },
                {
                    "question": "P-waves can travel through:",
                    "options": [
                    "Solids only",
                    "Liquids only",
                    "Solids, liquids, gases",
                    "None"
                    ],
                    "answer": "Solids, liquids, gases"
                },
                {
                    "question": "S-waves travel through:",
                    "options": ["Solids only", "Liquids", "Gases", "All"],
                    "answer": "Solids only"
                },
                {
                    "question": "Crust is:",
                    "options": ["Thickest", "Outermost", "Hottest", "Liquid"],
                    "answer": "Outermost"
                }
            ],
            "moderate": [
                {
                    "question": "Moho discontinuity lies between:",
                    "options": [
                    "Crust and mantle",
                    "Mantle and core",
                    "Core layers",
                    "Surface and crust"
                    ],
                    "answer": "Crust and mantle"
                },
                {
                    "question": "Asthenosphere is part of:",
                    "options": [
                    "Crust",
                    "Mantle",
                    "Core",
                    "Atmosphere"
                    ],
                    "answer": "Mantle"
                },
                {
                    "question": "Core mainly consists of:",
                    "options": [
                    "Silica",
                    "Iron and nickel",
                    "Carbon",
                    "Oxygen"
                    ],
                    "answer": "Iron and nickel"
                },
                {
                    "question": "Shadow zones help identify:",
                    "options": [
                    "Climate",
                    "Internal structure",
                    "Weather",
                    "Ocean currents"
                    ],
                    "answer": "Internal structure"
                },
                {
                    "question": "Gutenberg discontinuity separates:",
                    "options": [
                    "Crust and mantle",
                    "Mantle and core",
                    "Inner and outer core",
                    "Surface and mantle"
                    ],
                    "answer": "Mantle and core"
                }
            ],
            "advanced": [
                {
                    "question": "Consider the following:\n1. S-waves cannot pass through liquids\n2. Outer core is liquid\n3. Mantle is fully solid",
                    "options": ["1 and 2", "2 and 3", "1 and 3", "All"],
                    "answer": "1 and 2"
                },
                {
                    "question": "Which is correctly matched?",
                    "options": [
                    "SIAL – Crust",
                    "SIMA – Core",
                    "NIFE – Mantle",
                    "Moho – Core"
                    ],
                    "answer": "SIAL – Crust"
                },
                {
                    "question": "Which statement is correct?",
                    "options": [
                    "P-waves cannot pass liquids",
                    "S-waves pass liquids",
                    "Outer core is liquid",
                    "Crust is thickest"
                    ],
                    "answer": "Outer core is liquid"
                },
                {
                    "question": "Seismic waves help in:",
                    "options": [
                    "Weather prediction",
                    "Interior study",
                    "Ocean study",
                    "Climate change"
                    ],
                    "answer": "Interior study"
                },
                {
                    "question": "Inner core is solid due to:",
                    "options": [
                    "Low temperature",
                    "High pressure",
                    "Low density",
                    "Water"
                    ],
                    "answer": "High pressure"
                }
            ]
        }
    },
    {
        "name": "Interior of the Earth & Crust",
        "notes": [
            {
                "heading": "Interior of the Earth – Overview",
                "points": [
                    "Earth’s interior consists of three main layers: crust, mantle, and core",
                    "Layers differ in composition, density, and physical state",
                    "Knowledge mainly derived from seismic waves",
                    "Temperature, pressure, and density increase with depth",
                    "Understanding interior helps explain geological processes"
                ]
            },
            {
                "heading": "Crust – Overview",
                "points": [
                    "Outermost and thinnest layer of the Earth",
                    "Thickness varies from 5 km to 70 km",
                    "Represents less than 1% of Earth's volume",
                    "Highly important for human activities",
                    "Forms continents and ocean floors"
                ]
            },
            {
                "heading": "Types of Crust",
                "points": [
                    "Continental Crust – thick (30–70 km), less dense",
                    "Oceanic Crust – thin (5–10 km), more dense",
                    "Continental crust mainly granitic in composition",
                    "Oceanic crust mainly basaltic in composition",
                    "Oceanic crust is younger than continental crust"
                ]
            },
            {
                "heading": "Composition of Crust",
                "points": [
                    "Main elements: Oxygen, Silicon, Aluminum, Iron",
                    "Continental crust – SIAL (Silica + Alumina)",
                    "Oceanic crust – SIMA (Silica + Magnesium)",
                    "Rich in minerals and rocks",
                    "Important for natural resources"
                ]
            },
            {
                "heading": "Structure of Crust",
                "points": [
                    "Divided into upper and lower crust",
                    "Upper crust composed of lighter materials",
                    "Lower crust denser and more compact",
                    "Separated from mantle by Moho discontinuity",
                    "Thickness varies across regions"
                ]
            },
            {
                "heading": "Moho Discontinuity",
                "points": [
                    "Boundary between crust and mantle",
                    "Named after Andrija Mohorovičić",
                    "Identified using seismic wave velocity changes",
                    "Marks sudden increase in density",
                    "Important for UPSC"
                ]
            },
            {
                "heading": "Features of Continental Crust",
                "points": [
                    "Thicker than oceanic crust",
                    "Forms landmasses and continents",
                    "Contains older rocks (up to billions of years)",
                    "Less dense",
                    "More complex geological structure"
                ]
            },
            {
                "heading": "Features of Oceanic Crust",
                "points": [
                    "Thinner and denser",
                    "Forms ocean floor",
                    "Younger (generally less than 200 million years)",
                    "Continuously formed at mid-ocean ridges",
                    "Destroyed at subduction zones"
                ]
            },
            {
                "heading": "Importance of Crust",
                "points": [
                    "Supports life and ecosystems",
                    "Source of minerals and resources",
                    "Site of human settlements",
                    "Involved in tectonic activities",
                    "Plays role in earthquakes and volcanoes"
                ]
            }
        ],
        "mcqs": {
            "basic": [
                {
                    "question": "Crust is:",
                    "options": ["Innermost", "Middle", "Outermost", "Liquid"],
                    "answer": "Outermost"
                },
                {
                    "question": "Thickness of oceanic crust:",
                    "options": ["5–10 km", "30–70 km", "100 km", "500 km"],
                    "answer": "5–10 km"
                },
                {
                    "question": "Continental crust is:",
                    "options": ["Thin", "Thick", "Liquid", "Gas"],
                    "answer": "Thick"
                },
                {
                    "question": "SIAL refers to:",
                    "options": [
                    "Silica + Alumina",
                    "Silica + Magnesium",
                    "Iron + Nickel",
                    "Carbon + Oxygen"
                    ],
                    "answer": "Silica + Alumina"
                },
                {
                    "question": "Moho is between:",
                    "options": [
                    "Crust and mantle",
                    "Mantle and core",
                    "Core layers",
                    "Surface and crust"
                    ],
                    "answer": "Crust and mantle"
                }
            ],
            "moderate": [
                {
                    "question": "Oceanic crust is mainly:",
                    "options": ["Granitic", "Basaltic", "Sedimentary", "Metamorphic"],
                    "answer": "Basaltic"
                },
                {
                    "question": "Continental crust mainly consists of:",
                    "options": ["Basalt", "Granite", "Iron", "Gas"],
                    "answer": "Granite"
                },
                {
                    "question": "Moho discontinuity indicates:",
                    "options": [
                    "Change in climate",
                    "Change in density",
                    "Change in weather",
                    "Change in oceans"
                    ],
                    "answer": "Change in density"
                },
                {
                    "question": "Oceanic crust is younger because:",
                    "options": [
                    "Less formation",
                    "Continuous recycling",
                    "No movement",
                    "No erosion"
                    ],
                    "answer": "Continuous recycling"
                },
                {
                    "question": "Crust forms:",
                    "options": [
                    "Only land",
                    "Only ocean",
                    "Land and ocean floor",
                    "Core"
                    ],
                    "answer": "Land and ocean floor"
                }
            ],
            "advanced": [
                {
                    "question": "Consider the following:\n1. Continental crust is thicker\n2. Oceanic crust is denser\n3. Both have same composition",
                    "options": ["1 and 2", "2 and 3", "1 and 3", "All"],
                    "answer": "1 and 2"
                },
                {
                    "question": "Which is correctly matched?",
                    "options": [
                    "SIAL – Continental crust",
                    "SIMA – Continental crust",
                    "Moho – Core boundary",
                    "Crust – Thickest layer"
                    ],
                    "answer": "SIAL – Continental crust"
                },
                {
                    "question": "Which statement is correct?",
                    "options": [
                    "Oceanic crust is older",
                    "Continental crust is denser",
                    "Crust is thinnest layer",
                    "Moho is within core"
                    ],
                    "answer": "Crust is thinnest layer"
                },
                {
                    "question": "Main rock type of oceanic crust:",
                    "options": ["Granite", "Basalt", "Limestone", "Sandstone"],
                    "answer": "Basalt"
                },
                {
                    "question": "Crust accounts for:",
                    "options": [
                    "Major part of Earth",
                    "Less than 1%",
                    "Half of Earth",
                    "All of Earth"
                    ],
                    "answer": "Less than 1%"
                }
            ]
        }
    },
    {
        "name": "Mantle & Core",
        "notes": [
            {
                "heading": "Mantle – Overview",
                "points": [
                    "Layer between crust and core",
                    "Extends from Moho discontinuity to about 2900 km depth",
                    "Makes up about 83% of Earth’s volume",
                    "Composed mainly of silicate minerals rich in magnesium and iron",
                    "Semi-solid (plastic) in nature"
                ]
            },
            {
                "heading": "Structure of Mantle",
                "points": [
                    "Divided into upper mantle and lower mantle",
                    "Upper mantle includes lithosphere and asthenosphere",
                    "Asthenosphere is semi-molten and ductile",
                    "Lower mantle is more rigid due to high pressure",
                    "Temperature increases with depth"
                ]
            },
            {
                "heading": "Asthenosphere (Very Important)",
                "points": [
                    "Located in upper mantle (~100–350 km depth)",
                    "Soft, plastic layer",
                    "Plates float over it",
                    "Allows movement of tectonic plates",
                    "Responsible for earthquakes and volcanoes indirectly"
                ]
            },
            {
                "heading": "Convection Currents",
                "points": [
                    "Caused by heat from core",
                    "Hot material rises, cool material sinks",
                    "Drives plate tectonics",
                    "Responsible for continental drift",
                    "Key process shaping Earth’s surface"
                ]
            },
            {
                "heading": "Composition of Mantle",
                "points": [
                    "Mainly silica + magnesium (SIMA)",
                    "Rich in iron and magnesium minerals",
                    "Denser than crust",
                    "Less dense than core",
                    "Source of magma"
                ]
            },
            {
                "heading": "Core – Overview",
                "points": [
                    "Innermost layer of Earth",
                    "Extends from 2900 km to 6371 km",
                    "Composed mainly of iron and nickel (NIFE)",
                    "Very high temperature and pressure",
                    "Divided into outer core and inner core"
                ]
            },
            {
                "heading": "Outer Core",
                "points": [
                    "Located between 2900 km and 5150 km",
                    "In liquid state",
                    "S-waves cannot pass through it",
                    "Responsible for generating Earth’s magnetic field",
                    "Movement of molten metals creates dynamo effect"
                ]
            },
            {
                "heading": "Inner Core",
                "points": [
                    "Located from 5150 km to center (6371 km)",
                    "Solid despite high temperature",
                    "Due to extremely high pressure",
                    "Composed mainly of iron and nickel",
                    "Very dense region"
                ]
            },
            {
                "heading": "Discontinuities",
                "points": [
                    "Gutenberg discontinuity – mantle and outer core",
                    "Lehmann discontinuity – outer and inner core",
                    "Identified through seismic waves",
                    "Important boundaries inside Earth",
                    "Help understand structure"
                ]
            },
            {
                "heading": "Importance of Core",
                "points": [
                    "Source of Earth’s magnetic field",
                    "Protects Earth from solar radiation",
                    "Drives convection currents in mantle",
                    "Influences plate tectonics indirectly",
                    "Essential for life on Earth"
                ]
            }
        ],
        "mcqs": {
            "basic": [
                {
                    "question": "Mantle lies between:",
                    "options": [
                    "Crust and core",
                    "Core and atmosphere",
                    "Ocean and land",
                    "None"
                    ],
                    "answer": "Crust and core"
                },
                {
                    "question": "Core mainly consists of:",
                    "options": ["Silica", "Iron and nickel", "Carbon", "Oxygen"],
                    "answer": "Iron and nickel"
                },
                {
                    "question": "Outer core is:",
                    "options": ["Solid", "Liquid", "Gas", "Vacuum"],
                    "answer": "Liquid"
                },
                {
                    "question": "Inner core is:",
                    "options": ["Liquid", "Gas", "Solid", "Water"],
                    "answer": "Solid"
                },
                {
                    "question": "Asthenosphere is in:",
                    "options": ["Crust", "Mantle", "Core", "Atmosphere"],
                    "answer": "Mantle"
                }
            ],
            "moderate": [
                {
                    "question": "Convection currents occur in:",
                    "options": ["Crust", "Mantle", "Core", "Atmosphere"],
                    "answer": "Mantle"
                },
                {
                    "question": "S-waves cannot pass through:",
                    "options": ["Crust", "Mantle", "Outer core", "Inner core"],
                    "answer": "Outer core"
                },
                {
                    "question": "Gutenberg discontinuity lies between:",
                    "options": [
                    "Crust and mantle",
                    "Mantle and core",
                    "Inner and outer core",
                    "Surface and crust"
                    ],
                    "answer": "Mantle and core"
                },
                {
                    "question": "Asthenosphere is:",
                    "options": [
                    "Rigid",
                    "Plastic",
                    "Liquid",
                    "Gas"
                    ],
                    "answer": "Plastic"
                },
                {
                    "question": "Magnetic field is generated in:",
                    "options": ["Crust", "Mantle", "Outer core", "Inner core"],
                    "answer": "Outer core"
                }
            ],
            "advanced": [
                {
                    "question": "Consider the following:\n1. Mantle has convection currents\n2. Outer core is liquid\n3. Inner core is liquid",
                    "options": ["1 and 2", "2 and 3", "1 and 3", "All"],
                    "answer": "1 and 2"
                },
                {
                    "question": "Which is correctly matched?",
                    "options": [
                    "Asthenosphere – Plate movement",
                    "Core – SIAL",
                    "Mantle – NIFE",
                    "Crust – SIMA only"
                    ],
                    "answer": "Asthenosphere – Plate movement"
                },
                {
                    "question": "Which statement is correct?",
                    "options": [
                    "Outer core is solid",
                    "Inner core is liquid",
                    "Mantle drives plate movement",
                    "Core has no role in magnetism"
                    ],
                    "answer": "Mantle drives plate movement"
                },
                {
                    "question": "Inner core is solid due to:",
                    "options": [
                    "Low temperature",
                    "High pressure",
                    "Water",
                    "Air"
                    ],
                    "answer": "High pressure"
                },
                {
                    "question": "Lehmann discontinuity separates:",
                    "options": [
                    "Crust and mantle",
                    "Mantle and core",
                    "Outer and inner core",
                    "Surface and crust"
                    ],
                    "answer": "Outer and inner core"
                }
            ]
        }
    }
]