TOPICS = [
    {
        "name": "Sources of Information about Earth’s Interior",
        "notes": [
            {
                "heading": "Overview",
                "points": [
                    "Earth’s interior cannot be observed directly",
                    "Knowledge is based on indirect scientific methods",
                    "Information helps understand structure and composition",
                    "Important for studying earthquakes and tectonics",
                    "Divided into direct and indirect sources"
                ]
            },
            {
                "heading": "Direct Sources of Information",
                "points": [
                    "Mining – provides samples from shallow depths",
                    "Deep drilling projects – limited to few kilometers",
                    "Volcanic eruptions – bring material from inside Earth",
                    "Provide real but limited data",
                    "Cannot reach deeper layers"
                ]
            },
            {
                "heading": "Limitations of Direct Sources",
                "points": [
                    "Depth reached is very small compared to Earth’s radius",
                    "High temperature and pressure limit exploration",
                    "Expensive and technically difficult",
                    "Data not sufficient for full understanding",
                    "Hence reliance on indirect methods"
                ]
            },
            {
                "heading": "Indirect Sources of Information",
                "points": [
                    "Seismic waves (most important 🔥)",
                    "Gravity anomalies",
                    "Magnetic studies",
                    "Meteorites",
                    "Density calculations"
                ]
            },
            {
                "heading": "Seismic Waves (Very Important)",
                "points": [
                    "Generated by earthquakes",
                    "Travel through Earth’s interior",
                    "Change speed based on material",
                    "Help identify layers and boundaries",
                    "Key method for studying deep interior"
                ]
            },
            {
                "heading": "Types of Seismic Waves",
                "points": [
                    "P-waves (Primary) – travel through solids, liquids, gases",
                    "S-waves (Secondary) – travel only through solids",
                    "Surface waves – travel on surface, most destructive",
                    "Velocity changes indicate layer boundaries",
                    "Absence of S-waves indicates liquid layer"
                ]
            },
            {
                "heading": "Seismic Wave Behavior",
                "points": [
                    "Speed increases in denser materials",
                    "Refraction and reflection occur at boundaries",
                    "Shadow zones formed where waves do not reach",
                    "Helps locate core and mantle",
                    "Important conceptual topic"
                ]
            },
            {
                "heading": "Shadow Zones",
                "points": [
                    "Areas where seismic waves are absent",
                    "S-wave shadow zone confirms liquid outer core",
                    "P-wave shadow zone shows refraction",
                    "Provides evidence of Earth’s internal layers",
                    "Very important for UPSC"
                ]
            },
            {
                "heading": "Meteorites",
                "points": [
                    "Fragments from space that reach Earth",
                    "Composition similar to Earth’s interior",
                    "Provide clues about core materials",
                    "Contain iron and nickel",
                    "Important indirect evidence"
                ]
            },
            {
                "heading": "Gravity and Magnetic Studies",
                "points": [
                    "Gravity variations indicate density differences",
                    "Magnetic field generated by core",
                    "Helps understand internal structure",
                    "Used in geophysical surveys",
                    "Supports seismic data"
                ]
            },
            {
                "heading": "Density of Earth",
                "points": [
                    "Average density ~5.5 g/cm³",
                    "Higher than surface rocks",
                    "Indicates presence of dense core",
                    "Supports layered structure theory",
                    "Important indirect evidence"
                ]
            }
        ],
        "mcqs": {
            "basic": [
                {
                    "question": "Direct source of Earth’s interior:",
                    "options": ["Seismic waves", "Mining", "Gravity", "Magnetism"],
                    "answer": "Mining"
                },
                {
                    "question": "Most important indirect source:",
                    "options": ["Wind", "Seismic waves", "Rain", "Clouds"],
                    "answer": "Seismic waves"
                },
                {
                    "question": "P-waves travel through:",
                    "options": [
                    "Solids only",
                    "Liquids only",
                    "Solids, liquids, gases",
                    "None"
                    ],
                    "answer": "Solids, liquids, gases"
                },
                {
                    "question": "S-waves travel through:",
                    "options": ["Solids only", "Liquids", "Gases", "All"],
                    "answer": "Solids only"
                },
                {
                    "question": "Meteorites contain:",
                    "options": ["Water", "Iron and nickel", "Gas", "Sand"],
                    "answer": "Iron and nickel"
                }
            ],
            "moderate": [
                {
                    "question": "Shadow zones indicate:",
                    "options": [
                    "Weather",
                    "Interior structure",
                    "Ocean currents",
                    "Climate"
                    ],
                    "answer": "Interior structure"
                },
                {
                    "question": "Outer core is liquid because:",
                    "options": [
                    "Temperature low",
                    "S-waves absent",
                    "Water present",
                    "Air present"
                    ],
                    "answer": "S-waves absent"
                },
                {
                    "question": "Gravity anomalies indicate:",
                    "options": [
                    "Temperature",
                    "Density variation",
                    "Rainfall",
                    "Wind"
                    ],
                    "answer": "Density variation"
                },
                {
                    "question": "Direct sources are limited due to:",
                    "options": [
                    "Low temperature",
                    "High pressure",
                    "Wind",
                    "Rain"
                    ],
                    "answer": "High pressure"
                },
                {
                    "question": "Average density of Earth is:",
                    "options": ["1 g/cm³", "3 g/cm³", "5.5 g/cm³", "10 g/cm³"],
                    "answer": "5.5 g/cm³"
                }
            ],
            "advanced": [
                {
                    "question": "Consider the following:\n1. Seismic waves help study interior\n2. Meteorites provide composition clues\n3. Direct methods reach core",
                    "options": ["1 and 2", "2 and 3", "1 and 3", "All"],
                    "answer": "1 and 2"
                },
                {
                    "question": "Which is correctly matched?",
                    "options": [
                    "P-wave – All mediums",
                    "S-wave – Liquids",
                    "Meteorite – Atmosphere",
                    "Gravity – Wind"
                    ],
                    "answer": "P-wave – All mediums"
                },
                {
                    "question": "Which statement is correct?",
                    "options": [
                    "S-waves pass liquids",
                    "Direct sources reach deep core",
                    "Seismic waves reveal layers",
                    "Meteorites are gas bodies"
                    ],
                    "answer": "Seismic waves reveal layers"
                },
                {
                    "question": "Main evidence for liquid outer core:",
                    "options": [
                    "Gravity",
                    "S-wave absence",
                    "Temperature",
                    "Wind"
                    ],
                    "answer": "S-wave absence"
                },
                {
                    "question": "Refraction of waves indicates:",
                    "options": [
                    "Climate change",
                    "Layer boundaries",
                    "Rainfall",
                    "Ocean depth"
                    ],
                    "answer": "Layer boundaries"
                }
            ]
        }
    },
    {
        "name": "Direct & Indirect Sources (Earthquake Waves & Volcanoes)",
        "notes": [
            {
                "heading": "Overview",
                "points": [
                    "Earth’s interior is studied using direct and indirect sources",
                    "Direct sources provide actual samples but are limited",
                    "Indirect sources give detailed understanding through scientific methods",
                    "Earthquake waves and volcanoes are key indirect sources",
                    "Very important for UPSC conceptual questions"
                ]
            },
            {
                "heading": "Direct Sources",
                "points": [
                    "Mining activities provide rock samples",
                    "Deep drilling projects reach a few kilometers",
                    "Volcanic materials sometimes considered semi-direct evidence",
                    "Provide real physical data",
                    "Limited to shallow depths"
                ]
            },
            {
                "heading": "Limitations of Direct Sources",
                "points": [
                    "Cannot reach deep interior",
                    "High temperature and pressure restrict access",
                    "Very costly and technically difficult",
                    "Limited geographical coverage",
                    "Hence less reliable for full structure"
                ]
            },
            {
                "heading": "Indirect Sources – Overview",
                "points": [
                    "Main method to study deep Earth",
                    "Include seismic waves, volcanoes, gravity, magnetism",
                    "Provide continuous and wide data",
                    "Highly reliable for interior study",
                    "Most important for UPSC"
                ]
            },
            {
                "heading": "Earthquake Waves (Seismic Waves)",
                "points": [
                    "Generated during earthquakes",
                    "Travel through Earth’s interior",
                    "Velocity depends on material density",
                    "Help identify layers and boundaries",
                    "Primary tool for interior study"
                ]
            },
            {
                "heading": "Types of Earthquake Waves",
                "points": [
                    "P-waves – fastest, travel through solids, liquids, gases",
                    "S-waves – slower, travel only through solids",
                    "Surface waves – travel along surface, most destructive",
                    "Different behaviors reveal internal structure",
                    "Key concept for exams"
                ]
            },
            {
                "heading": "Seismic Evidence",
                "points": [
                    "S-waves absent in outer core → proves it is liquid",
                    "P-waves refracted in core → indicates density change",
                    "Shadow zones confirm layered structure",
                    "Wave speed increases with depth",
                    "Helps locate discontinuities"
                ]
            },
            {
                "heading": "Volcanoes as Indirect Source",
                "points": [
                    "Erupt molten material (magma) from interior",
                    "Provide information about mantle composition",
                    "Bring gases and minerals from deep layers",
                    "Help understand temperature and pressure conditions",
                    "Important complementary evidence"
                ]
            },
            {
                "heading": "Volcanic Materials",
                "points": [
                    "Lava – molten rock on surface",
                    "Magma – molten rock inside Earth",
                    "Gases – water vapor, CO2, sulfur",
                    "Ash and rock fragments",
                    "Reflect composition of mantle"
                ]
            },
            {
                "heading": "Importance of Volcanoes",
                "points": [
                    "Reveal internal composition",
                    "Help understand mantle processes",
                    "Provide minerals and rocks",
                    "Linked with plate tectonics",
                    "Important for geological studies"
                ]
            }
        ],
        "mcqs": {
            "basic": [
                {
                    "question": "Direct source includes:",
                    "options": ["Seismic waves", "Mining", "Gravity", "Magnetism"],
                    "answer": "Mining"
                },
                {
                    "question": "Main indirect source:",
                    "options": ["Wind", "Seismic waves", "Rain", "Clouds"],
                    "answer": "Seismic waves"
                },
                {
                    "question": "P-waves travel through:",
                    "options": [
                    "Solids only",
                    "Liquids only",
                    "Solids, liquids, gases",
                    "None"
                    ],
                    "answer": "Solids, liquids, gases"
                },
                {
                    "question": "S-waves cannot travel through:",
                    "options": ["Solids", "Liquids", "Gases", "Surface"],
                    "answer": "Liquids"
                },
                {
                    "question": "Volcanoes bring material from:",
                    "options": ["Atmosphere", "Interior", "Ocean", "Surface"],
                    "answer": "Interior"
                }
            ],
            "moderate": [
                {
                    "question": "Outer core is liquid because:",
                    "options": [
                    "Low temperature",
                    "S-waves absent",
                    "High pressure",
                    "Water present"
                    ],
                    "answer": "S-waves absent"
                },
                {
                    "question": "Magma becomes lava when:",
                    "options": [
                    "Inside Earth",
                    "Reaches surface",
                    "Cools down",
                    "Mixes with air"
                    ],
                    "answer": "Reaches surface"
                },
                {
                    "question": "Volcanic gases mainly include:",
                    "options": [
                    "Oxygen",
                    "CO2 and water vapor",
                    "Nitrogen only",
                    "Helium"
                    ],
                    "answer": "CO2 and water vapor"
                },
                {
                    "question": "Seismic waves help in:",
                    "options": [
                    "Weather",
                    "Interior study",
                    "Ocean currents",
                    "Climate"
                    ],
                    "answer": "Interior study"
                },
                {
                    "question": "Shadow zones indicate:",
                    "options": [
                    "Climate",
                    "Interior layers",
                    "Rainfall",
                    "Wind"
                    ],
                    "answer": "Interior layers"
                }
            ],
            "advanced": [
                {
                    "question": "Consider the following:\n1. Volcanoes provide interior material\n2. S-waves pass through liquids\n3. P-waves show refraction",
                    "options": ["1 and 3", "2 and 3", "1 and 2", "All"],
                    "answer": "1 and 3"
                },
                {
                    "question": "Which is correctly matched?",
                    "options": [
                    "P-wave – All mediums",
                    "S-wave – Liquids",
                    "Volcano – Atmosphere",
                    "Mining – Deep core"
                    ],
                    "answer": "P-wave – All mediums"
                },
                {
                    "question": "Which statement is correct?",
                    "options": [
                    "Direct sources reach core",
                    "Seismic waves reveal structure",
                    "Volcanoes show atmosphere",
                    "S-waves travel liquids"
                    ],
                    "answer": "Seismic waves reveal structure"
                },
                {
                    "question": "Main evidence for core composition:",
                    "options": [
                    "Wind",
                    "Seismic waves and meteorites",
                    "Rain",
                    "Clouds"
                    ],
                    "answer": "Seismic waves and meteorites"
                },
                {
                    "question": "Volcanoes mainly indicate:",
                    "options": [
                    "Weather",
                    "Mantle composition",
                    "Ocean depth",
                    "Climate"
                    ],
                    "answer": "Mantle composition"
                }
            ]
        }
    }
]